version: "3"
services:
  backend:
    build: .
    container_name: schennel_node
    environment:
      - 'NODE_ENV=production'
    depends_on:
      - db
    restart: 'on-failure:5'
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - net
    
  db:
    image: mysql
    container_name: schennel_mysql
    restart: unless-stopped
    volumes:
      - schennel-mysql:/var/lib/mysql
    environment:
      TZ: Asia/Seoul
    env_file:
      - .env
    ports:
      - 3306:3306
    networks:
      - net

volumes:
  schennel-mysql:
networks:
  net: