version: "3"
services:
  backend:
    build: .
    container_name: route_node
    environment:
      - 'NODE_ENV=production'
    depends_on:
      - db
    restart: 'on-failure:5'
    ports:
      - 3921:8000
    networks:
      - net
    
  db:
    image: mysql
    container_name: route_mysql
    restart: unless-stopped
    volumes:
      - route-mysql:/var/lib/mysql
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: Super-Easy-Passw0rd
    networks:
      - net

volumes:
  route-mysql:
networks:
  net: